SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE calls;
TRUNCATE TABLE agents;
TRUNCATE TABLE clients;
TRUNCATE TABLE users;
TRUNCATE TABLE servers;
TRUNCATE TABLE jobs;
TRUNCATE TABLE cache;

SET FOREIGN_KEY_CHECKS=1; 